'use client';
import {useEffect,useRef,useState} from 'react';
import gsap from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import {products,reviews} from './content';
gsap.registerPlugin(ScrollTrigger);
const assetPrefix=process.env.NEXT_PUBLIC_ASSET_PREFIX||'';
const asset=(path:string)=>`${assetPrefix}${path}`;
function Flame({className=''}:{className?:string}){return <svg className={className} viewBox="0 0 32 38" fill="currentColor" aria-hidden="true"><path d="M18 1C20 12 30 15 30 25A14 14 0 0 1 2 25c0-7 4-11 7-16 0 8 3 10 5 6C17 9 18 5 18 1Zm-1 20c-1 4-7 7-7 11a6 6 0 0 0 12 0c0-4-4-6-5-11Z"/></svg>}
function Arrow(){return <span aria-hidden="true">↗</span>}
type Cart=Record<string,number>;
export default function Home(){const root=useRef<HTMLElement>(null);const [filter,setFilter]=useState('all'),[cart,setCart]=useState<Cart>({}),[ready,setReady]=useState(false),[drawer,setDrawer]=useState(false),[menu,setMenu]=useState(false),[toast,setToast]=useState(''),[promo,setPromo]=useState(false),[promoInput,setPromoInput]=useState(''),[message,setMessage]=useState(''),[motion,setMotion]=useState(true),[ordered,setOrdered]=useState(false);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('hot-club-cart')||'{}');const clean:Cart={};products.forEach(p=>{if(Number.isInteger(saved[p.id])&&saved[p.id]>0)clean[p.id]=Math.min(saved[p.id],99)});setCart(clean)}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('hot-club-cart',JSON.stringify(cart))}catch{}},[cart,ready]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2600);return()=>clearTimeout(t)},[toast]);
 useEffect(()=>{const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{if(!motion)return;const ctx=gsap.context(()=>{gsap.from('.hero-copy>*',{y:35,opacity:0,stagger:.12,duration:.8,ease:'power3.out'});gsap.to('.hero-art',{yPercent:9,scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1}});gsap.utils.toArray<HTMLElement>('.reveal').forEach(el=>gsap.from(el,{y:40,opacity:0,duration:.7,scrollTrigger:{trigger:el,start:'top 93%',once:true}}));gsap.to('.club-art img',{yPercent:-7,scrollTrigger:{trigger:'.club',start:'top bottom',end:'bottom top',scrub:1}})},root);return()=>ctx.revert()});return()=>mm.revert()},[motion]);
 const count=Object.values(cart).reduce((a,b)=>a+b,0);const subtotal=products.reduce((a,p)=>a+p.price*(cart[p.id]||0),0);const discount=promo?Math.round(subtotal*.15):0;
 function add(id:string){setCart(c=>({...c,[id]:Math.min((c[id]||0)+1,99)}));setOrdered(false);setToast(`${products.find(p=>p.id===id)?.name} — в корзине`)}
 function change(id:string,n:number){setCart(c=>{const next={...c,[id]:Math.max(0,Math.min((c[id]||0)+n,99))};if(next[id]===0)delete next[id];return next});setOrdered(false)}
 function pack(){setCart(c=>{const next={...c};products.forEach(p=>next[p.id]=Math.min((next[p.id]||0)+1,99));return next});setPromo(true);setPromoInput('HOT15');setMessage('HOT15 применён: −15%');setOrdered(false);setDrawer(true)}
 const visible=products.filter(p=>filter==='all'||(filter==='soft'?p.heat<=3:p.heat>=4));
 return <main ref={root} className={!motion?'paused':''}><a href="#flavors" className="skip">Перейти к вкусам</a><div className="topbar"><span>НЕ ДЛЯ СКУЧНЫХ УЖИНОВ</span><span>−15% НА ПЕРВЫЙ ОГОНЬ · <button onClick={()=>{setPromo(true);setPromoInput('HOT15');setToast('Промокод HOT15 активирован')}}>HOT15 ↗</button></span><span>SEOUL HEAT / TOKYO VIBE</span></div><header><a href="#home" className="logo" aria-label="Buldak Hot Club — главная"><Flame/><span>BULDAK<small>HOT CLUB</small></span></a><nav className={menu?'open':''} id="nav">{[['Вкусы','flavors'],['Наш вайб','club'],['Отзывы','reviews']].map(([s,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{s}</a>)}<a href="#deal" onClick={()=>setMenu(false)}>Акции <span className="nav-dot"/></a></nav><div className="nav-actions"><button className="menu" aria-expanded={menu} aria-controls="nav" onClick={()=>setMenu(!menu)}>{menu?'Закрыть':'Меню'}</button><button className="cart-button" onClick={()=>setDrawer(true)} aria-label={`Корзина: ${count} товаров`}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 7h14l1 14H4L5 7Zm3 0V5a4 4 0 0 1 8 0v2"/></svg><span className="cart-label">Корзина</span><b>{count}</b></button></div></header>
 <section className="hero" id="home"><div className="hero-art"><img src={asset('/mascots.webp')} alt="Две взрослые anime-героини с огненной лапшой в стиле streetwear" fetchPriority="high" width="1536" height="1024"/></div><div className="embers" aria-hidden="true">{Array.from({length:12},(_,i)=><i key={i} style={{left:`${43+i*4.5}%`,animationDelay:`${i*-.7}s`,animationDuration:`${3+i%4}s`}}/>)}</div><div className="hero-copy"><p className="eyebrow"><span/> KOREAN RAMEN. ANIME ENERGY.</p><h1>МИЛО<br/><span>НЕ БУДЕТ</span><b>でも、おいしい。</b></h1><p className="hero-description">Влюбись во вкус. Выдержи огонь.<br/>Твой новый краш — корейская лапша Buldak.</p><div className="hero-ctas"><a href="#flavors" className="button primary">ВЫБРАТЬ СВОЙ ОГОНЬ <Arrow/></a><a className="text-link" href="#deal">Хочу всё сразу <span>↗</span></a></div><div className="hero-meta"><div className="mini-packs"><img src={asset('/carbonara.webp')} alt="" width="55" height="50"/><img src={asset('/original.webp')} alt="" width="55" height="50"/><img src={asset('/2x.webp')} alt="" width="55" height="50"/></div><p><strong>4 вкуса. Один hot club.</strong><br/>Найди свой уровень остроты.</p></div></div><div className="heat-sticker"><Flame/><span>CAUTION</span><b>VERY HOT</b></div><div className="hero-bottom"><span>辛いほど、好きになる。 / ОСТРОТА, В КОТОРУЮ ВЛЮБЛЯЮТСЯ</span><a href="#flavors">SCROLL TO FEEL THE HEAT ↓</a></div></section>
 <div className="ticker" aria-hidden="true"><div>{Array.from({length:4},(_,i)=><span key={i}>HOT NOODLES <Flame/> COOL PEOPLE <span className="outline">NO BORING BITES</span> <Flame/></span>)}</div></div>
 <section className="catalog section" id="flavors"><div className="section-top reveal"><div><p className="eyebrow">01 / CHOOSE YOUR PLAYER</p><h2>ТВОЙ ВКУС.<br/><span>ТВОИ ПРАВИЛА.</span></h2></div><div className="catalog-right"><p>От сливочного флирта<br/>до двойного пожара.</p><div className="filters" aria-label="Фильтр по остроте">{[['all','Все вкусы'],['soft','Помягче'],['hot','Погорячее']].map(([id,label])=><button key={id} aria-pressed={filter===id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label}</button>)}</div></div></div><div className="products">{visible.map((p,i)=><article className={'product product-'+p.id} key={p.id} style={{'--card':p.color} as React.CSSProperties}><div className="product-top"><span>{p.badge}</span><span>0{products.indexOf(p)+1} ↗</span></div><div className="product-image"><div className="product-ring"/><span className="product-jp" aria-hidden="true">{p.id==='2x'?'激辛':'うまい'}</span><img src={asset(`/${p.id}.webp`)} alt={`Упаковка Buldak ${p.name}`} width="400" height="330" loading="lazy"/></div><div className="product-copy"><p className="product-tag">{p.tag}</p><h3>{p.name}</h3><p className="product-desc">{p.desc}</p><div className="heat"><span>УРОВЕНЬ ЖАРА</span><span aria-label={`Острота ${p.heat} из 5`}>{Array.from({length:5},(_,i)=><Flame key={i} className={i<p.heat?'lit':'unlit'}/>)}</span></div><div className="product-buy"><div><strong>{p.price} ₽</strong><small>1 упаковка / {p.weight}</small></div><button onClick={()=>add(p.id)} aria-label={`Добавить ${p.name} в корзину`}><span>В корзину</span> +</button></div></div></article>)}</div><p className="fineprint">Цены — для демо. Шкала жара — условная оценка магазина, не SHU.</p></section>
 <section className="club section" id="club"><div className="club-art"><img src={asset('/mascots.webp')} alt="Anime-маскоты Hot Club с горячей лапшой" width="1536" height="1024" loading="lazy"/><span className="club-label">HOT GIRLS. HOT NOODLES.</span></div><div className="club-copy reveal"><p className="eyebrow">02 / WELCOME TO THE HOT CLUB</p><h2>СЛИШКОМ<br/>ЯРКО, ЧТОБЫ<br/><em>ОСТЫТЬ.</em></h2><p>Ночной плейлист. Любимое аниме.<br/>И лапша, которая делает вечер громче.</p><p>Мы за вкус с характером, смелые сочетания<br/>и ещё одну порцию. Ты с нами?</p><a href="#flavors" className="button pink">Я В КЛУБЕ <Arrow/></a><div className="club-note"><span>韓国の味</span>КОРЕЙСКИЙ ВКУС × JAPANESE POP</div></div></section>
 <section className="deal section" id="deal"><div className="deal-copy reveal"><span className="deal-label">FIRST BITE / FIRST LOVE</span><h2>ПЕРВОЕ<br/>СВИДАНИЕ<br/><span>С ОГНЁМ.</span></h2><p>Собери все четыре вкуса.<br/>Найди любимый и получи −15% с HOT15.</p><button className="button black" onClick={pack}>ЗАБРАТЬ МИКС ЗА 847 ₽ <Arrow/></button><small>Демонстрационная акция · 4 упаковки вместо 996 ₽</small></div><div className="deal-visual"><span className="discount">−15<small>%</small></span><div className="deal-burst" aria-hidden="true"/>{products.map((p,i)=><img key={p.id} className={'deal-pack pack-'+i} src={asset(`/${p.id}.webp`)} alt={p.name} loading="lazy" width="260" height="260"/>)}<span className="deal-stamp">ALL FLAVORS<br/>ALL FEELINGS</span></div></section>
 <section className="reviews section" id="reviews"><div className="section-top reveal"><div><p className="eyebrow">03 / LOVE AT FIRST BITE</p><h2>ОСТРО.<br/><span>ЗАТО ОТ ДУШИ.</span></h2></div><p className="review-note">Так мог бы звучать наш hot club.<br/>Примеры отзывов для концепции.</p></div><div className="review-grid">{reviews.map(r=><figure className="review reveal" key={r.name}><div className="review-stars" aria-label="Оценка 5 из 5">★★★★★ <span>“</span></div><blockquote>{r.text}</blockquote><figcaption><span className="avatar" style={{background:r.color}}>{r.avatar}</span><div><b>{r.name}</b><small>{r.handle}</small></div><span className="review-team">{r.flavor}</span></figcaption></figure>)}</div></section>
 <footer><div className="footer-top"><a className="logo" href="#home"><Flame/><span>BULDAK<small>HOT CLUB</small></span></a><p>НЕ ОСТАВЛЯЙ ВЕЧЕР ПРЕСНЫМ.</p><a href="#flavors" className="footer-arrow" aria-label="Перейти к вкусам">↗</a></div><div className="footer-bottom"><span>© 2026 HOT CLUB · Независимая демо-концепция, не официальный магазин Buldak.</span><button aria-pressed={!motion} onClick={()=>setMotion(!motion)}>{motion?'Анимации: вкл.':'Анимации: выкл.'}</button><a href="https://buldak.com/uk/product/" target="_blank" rel="noreferrer">О продукции ↗</a></div></footer>
 <div className={'toast '+(toast?'show':'')} role="status">{toast} <span>✓</span></div>
 {drawer&&<CartDialog close={()=>setDrawer(false)}><div className="cart-heading"><p className="eyebrow">YOUR HOT SELECTION</p><h2>ТВОЙ ОГОНЬ <span>({count})</span></h2></div>{count===0?<div className="empty"><Flame/><h3>Пока не горячо.</h3><p>Добавь свой первый вкус.</p><button className="button primary" onClick={()=>{setDrawer(false);document.getElementById('flavors')?.scrollIntoView({behavior:'auto'})}}>ВЫБРАТЬ ЛАПШУ <Arrow/></button></div>:<><div className="cart-items">{products.filter(p=>cart[p.id]).map(p=><div className="cart-item" key={p.id}><img src={asset(`/${p.id}.webp`)} alt="" width="80" height="80"/><div><h3>{p.name}</h3><p>{p.price} ₽ / шт.</p><div className="quantity"><button onClick={()=>change(p.id,-1)} aria-label={`Убрать одну ${p.name}`}>−</button><span>{cart[p.id]}</span><button onClick={()=>change(p.id,1)} aria-label={`Добавить одну ${p.name}`}>+</button></div></div><strong>{p.price*cart[p.id]} ₽</strong></div>)}</div><form className="promo-form" onSubmit={e=>{e.preventDefault();if(promoInput.trim().toUpperCase()==='HOT15'){setPromo(true);setMessage('HOT15 применён: −15%')}else{setPromo(false);setMessage('Код не найден. Попробуй HOT15.')}}}><label htmlFor="promo">Есть промокод?</label><div><input id="promo" value={promoInput} onChange={e=>setPromoInput(e.target.value)} placeholder="HOT15"/><button type="submit">Применить ↗</button></div><p role="status">{message}</p></form><div className="cart-total"><p>Товары <span>{subtotal} ₽</span></p>{promo&&<p className="saving">Скидка HOT15 <span>−{discount} ₽</span></p>}<strong>ИТОГО <span>{subtotal-discount} ₽</span></strong></div><button className="button primary checkout" onClick={()=>setOrdered(true)}>ОФОРМИТЬ · ДЕМО <Arrow/></button>{ordered&&<p className="order-message" role="status">Всё готово: {count} шт. на {subtotal-discount} ₽. Это демо-магазин — заказ не отправлен, оплата не списывается.</p>}<p className="cart-disclaimer">Покупка и доставка пока не подключены.</p></>}</CartDialog>}
 </main>
}
function CartDialog({children,close}:{children:React.ReactNode,close:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const last=document.activeElement as HTMLElement;ref.current?.showModal();const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old;last?.focus()}},[]);return <dialog ref={ref} aria-label="Корзина" onCancel={close} onClick={e=>{if(e.target===ref.current)close()}}><div className="drawer-content"><button className="close" onClick={close} aria-label="Закрыть корзину">×</button>{children}</div></dialog>}
